/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TapWaterSoundIndexRouteImport } from './routes/tap-water-sound.index'
import { Route as TapWaterSoundSupportIndexRouteImport } from './routes/tap-water-sound.support.index'
import { Route as TapWaterSoundPrivacyPolicyIndexRouteImport } from './routes/tap-water-sound.privacy-policy.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TapWaterSoundIndexRoute = TapWaterSoundIndexRouteImport.update({
  id: '/tap-water-sound/',
  path: '/tap-water-sound/',
  getParentRoute: () => rootRouteImport,
} as any)
const TapWaterSoundSupportIndexRoute =
  TapWaterSoundSupportIndexRouteImport.update({
    id: '/tap-water-sound/support/',
    path: '/tap-water-sound/support/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TapWaterSoundPrivacyPolicyIndexRoute =
  TapWaterSoundPrivacyPolicyIndexRouteImport.update({
    id: '/tap-water-sound/privacy-policy/',
    path: '/tap-water-sound/privacy-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tap-water-sound/': typeof TapWaterSoundIndexRoute
  '/tap-water-sound/privacy-policy/': typeof TapWaterSoundPrivacyPolicyIndexRoute
  '/tap-water-sound/support/': typeof TapWaterSoundSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tap-water-sound': typeof TapWaterSoundIndexRoute
  '/tap-water-sound/privacy-policy': typeof TapWaterSoundPrivacyPolicyIndexRoute
  '/tap-water-sound/support': typeof TapWaterSoundSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tap-water-sound/': typeof TapWaterSoundIndexRoute
  '/tap-water-sound/privacy-policy/': typeof TapWaterSoundPrivacyPolicyIndexRoute
  '/tap-water-sound/support/': typeof TapWaterSoundSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tap-water-sound/'
    | '/tap-water-sound/privacy-policy/'
    | '/tap-water-sound/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tap-water-sound'
    | '/tap-water-sound/privacy-policy'
    | '/tap-water-sound/support'
  id:
    | '__root__'
    | '/'
    | '/tap-water-sound/'
    | '/tap-water-sound/privacy-policy/'
    | '/tap-water-sound/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TapWaterSoundIndexRoute: typeof TapWaterSoundIndexRoute
  TapWaterSoundPrivacyPolicyIndexRoute: typeof TapWaterSoundPrivacyPolicyIndexRoute
  TapWaterSoundSupportIndexRoute: typeof TapWaterSoundSupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap-water-sound/': {
      id: '/tap-water-sound/'
      path: '/tap-water-sound'
      fullPath: '/tap-water-sound/'
      preLoaderRoute: typeof TapWaterSoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap-water-sound/support/': {
      id: '/tap-water-sound/support/'
      path: '/tap-water-sound/support'
      fullPath: '/tap-water-sound/support/'
      preLoaderRoute: typeof TapWaterSoundSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap-water-sound/privacy-policy/': {
      id: '/tap-water-sound/privacy-policy/'
      path: '/tap-water-sound/privacy-policy'
      fullPath: '/tap-water-sound/privacy-policy/'
      preLoaderRoute: typeof TapWaterSoundPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TapWaterSoundIndexRoute: TapWaterSoundIndexRoute,
  TapWaterSoundPrivacyPolicyIndexRoute: TapWaterSoundPrivacyPolicyIndexRoute,
  TapWaterSoundSupportIndexRoute: TapWaterSoundSupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
