/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BathroomWaterIndexRouteImport } from './routes/bathroom-water.index'
import { Route as BathroomWaterSupportIndexRouteImport } from './routes/bathroom-water.support.index'
import { Route as BathroomWaterPrivacyPolicyIndexRouteImport } from './routes/bathroom-water.privacy-policy.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BathroomWaterIndexRoute = BathroomWaterIndexRouteImport.update({
  id: '/bathroom-water/',
  path: '/bathroom-water/',
  getParentRoute: () => rootRouteImport,
} as any)
const BathroomWaterSupportIndexRoute =
  BathroomWaterSupportIndexRouteImport.update({
    id: '/bathroom-water/support/',
    path: '/bathroom-water/support/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BathroomWaterPrivacyPolicyIndexRoute =
  BathroomWaterPrivacyPolicyIndexRouteImport.update({
    id: '/bathroom-water/privacy-policy/',
    path: '/bathroom-water/privacy-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bathroom-water/': typeof BathroomWaterIndexRoute
  '/bathroom-water/privacy-policy/': typeof BathroomWaterPrivacyPolicyIndexRoute
  '/bathroom-water/support/': typeof BathroomWaterSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bathroom-water': typeof BathroomWaterIndexRoute
  '/bathroom-water/privacy-policy': typeof BathroomWaterPrivacyPolicyIndexRoute
  '/bathroom-water/support': typeof BathroomWaterSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bathroom-water/': typeof BathroomWaterIndexRoute
  '/bathroom-water/privacy-policy/': typeof BathroomWaterPrivacyPolicyIndexRoute
  '/bathroom-water/support/': typeof BathroomWaterSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bathroom-water/'
    | '/bathroom-water/privacy-policy/'
    | '/bathroom-water/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bathroom-water'
    | '/bathroom-water/privacy-policy'
    | '/bathroom-water/support'
  id:
    | '__root__'
    | '/'
    | '/bathroom-water/'
    | '/bathroom-water/privacy-policy/'
    | '/bathroom-water/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BathroomWaterIndexRoute: typeof BathroomWaterIndexRoute
  BathroomWaterPrivacyPolicyIndexRoute: typeof BathroomWaterPrivacyPolicyIndexRoute
  BathroomWaterSupportIndexRoute: typeof BathroomWaterSupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-water/': {
      id: '/bathroom-water/'
      path: '/bathroom-water'
      fullPath: '/bathroom-water/'
      preLoaderRoute: typeof BathroomWaterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-water/support/': {
      id: '/bathroom-water/support/'
      path: '/bathroom-water/support'
      fullPath: '/bathroom-water/support/'
      preLoaderRoute: typeof BathroomWaterSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-water/privacy-policy/': {
      id: '/bathroom-water/privacy-policy/'
      path: '/bathroom-water/privacy-policy'
      fullPath: '/bathroom-water/privacy-policy/'
      preLoaderRoute: typeof BathroomWaterPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BathroomWaterIndexRoute: BathroomWaterIndexRoute,
  BathroomWaterPrivacyPolicyIndexRoute: BathroomWaterPrivacyPolicyIndexRoute,
  BathroomWaterSupportIndexRoute: BathroomWaterSupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
